### ISSUE TITLE
Siri doesn't work anymore, even after uninstall :-(

### ISSUE THREAD

**Issue by blueman007** [0xkuj/SiriTTL#1] opened 2020-06-28 13:37 UTC
Hi,

After installing SIRI TLL, Siri doesn't launch anymore. The phone does not respond to "Hey Siri", and if launched with a double-click of the side-button, the Siri windows appears briefly and is dismissed immediately, as if Siri TTL would be set to zero seconds.
Worse, the behavior stays the same if the tweak is uninstalled, so Siri assistant is completely non-functional on my device.
The only parts that still works is Siri talking to me, for example if I use "says with Siri" in shortcuts, so I know that the text to speech function works, but that's it.

Any help would be appreciated,

So far I have tried to : 
- restart the phone,
- enable/disable the tweak in its settings panel,
- install/deinstall/reinstall Siri TTL Tweak in Cydia,
- set TTL duration to something else (ex: 30  seconds),
- with SiriTTL uninstalled, disable "listen to hey siri", disable "launch with side-button", and then enable them,
- trigger Siri using the tweak SiriAPP, which launch Siri from a homescreen icon,

None of this works or has changed anything.

Siri TTL 1.0 on Iphone XR, IOS 13.5, Unc0ver 5.01

**Comment by 0xkuj** [comment] 2020-06-28 13:47
Hi!
Thank you for your feedback.
Unfortunately, it seems like this tweak has nothing to do with your problem.
I will explain:
- The way this tweak work (you can watch the code) is by hooking classes and functions, in this case, we hook a class that is related to Siri assistant, and override the original Apple's function - this function is the function that is being called when the Siri status is changed (getting inside idle mode or the opposite).
Since you said that you **uninstalled** the tweak, the hook is no longer exists, which means that the code doesn't exist. 

I will suggest you will remove this tweak completely, and also reboot your phone into unjailbroken state - and then check:
if this issue continue when unjailbroken - it is NOT jailbreak related. probably something is corrupted (not this tweak fault) with your system files.
if the issue is gone when unjailbroken (<--- the probable option) - You have **installed** a tweak that is causing this issue. find the tweak and remove it (Or - use icleaner to cancel all your tweaks and then turn them on one by one until the culprit is found)

**Comment by blueman007** [comment] 2020-06-28 13:51
Thanks for the quick feedback,
Unfortunately, the issue is the same after reboot in unjailbroken state. I will try to investigate further but I don't want to loose my JB.

**Comment by 0xkuj** [comment] 2020-06-28 13:57
> Thanks for the quick feedback,
> Unfortunately, the issue is the same after reboot in unjailbroken state. I will try to investigate further but I don't want to loose my JB.

you don't need to lose your jailbreak, but if this happens in the original state of iOS then it is not jailbreak/any tweak related. 
it may be in your settings, or files you copied/removed using Filza, as last resort use one of the following options (note - all data will be removed)
1. use "succession" tweak in order to restore the iOS version without updating (and without losing JB ofc)
2. a. rootfs and then b. remove all data and settings. 

both of the options above will restore iOS default system settings (and will delete all your data).
if this is important to you, and you could not find any other proper fix, I would go on one of these options.

I am closing this issue since it is not tweak related,
let me know if any further assistance is needed.

**Closed as completed by 0xkuj** 2020-06-28 13:57 UTC
